### ISSUE TITLE
'Contributors' field of collections doesn't work correctly

### ISSUE THREAD

**Issue by jbwexler** [NeuroVault/NeuroVault#110]
When I type in text in the 'contributors' field and save the collection, the page reloads, this time no longer displaying the 'contributors' field. In order to see if the text I entered had been saved, I queried for the collection's contributors in the django shell. This was the result: 

StopIteration                             Traceback (most recent call last)
<ipython-input-16-b0845da5f9c6> in <module>()
----> 1 print mycollection.contributors

/Users/jbwexler/anaconda/lib/python2.7/site-packages/django/utils/encoding.pyc in <lambda>(self)
     36                              klass.__name__)
     37         klass.__unicode__ = klass.__str__
---> 38         klass.__str__ = lambda self: self.__unicode__().encode('utf-8')
     39     return klass
     40

/Users/jbwexler/anaconda/lib/python2.7/site-packages/django/db/models/manager.pyc in __str__(self)
     79         app = model._meta.app_label
     80         manager_name = next(name for (_, name, manager)
---> 81             in opts.concrete_managers + opts.abstract_managers
     82             if manager == self)
     83         return '%s.%s.%s' % (app, model._meta.object_name, manager_name)

I am wondering if the issue may be due to an issue in the migration history because I can't locate in the history when the 'contributors' field was updated to its current state. It should also be noted that this field is the only field in the app that is a ManyToManyField.

**Comment by chrisfilo** [comment]
I can replicate this.

**Comment by infocortex** [comment]
It was a crispy forms issue, it aggressively caches the rendered form html and doesn't respect `Meta.exclude()` changing
