### ISSUE TITLE
cannot alter fields in particular forms in formset

### ISSUE THREAD

**Issue by jbwexler** [NeuroVault/NeuroVault#113]
I am trying to add a feature to the 'edit images' page of a collection. it should add a new field (which was previously hidden) only to the statistical map forms that have a particular error message. but when I try to change only these forms (either in views or in forms), it changes all of statistical map forms (but not the atlas forms). i didn't have this issue with the old version of the 'edit images' page and i think it may have something to do with polymorphic models. so does anyone know why changing one form would change all of them?

**Comment by vsoch** [comment]
Can you link to where you are making the change?
