### ISSUE TITLE
Edit images dialog does not indicate errors if collection is empty

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#114]
Steps to replicate

1. Create a new collection
2. Start adding an image, but miss one of the compulsory fields
3. Press save

Result:
the form disappears instead of showing missing fields in red. In addition the form becomes useless - it does not work even if you fill all of the compulsory fields. You need to reload the page to make it usable again.

**Comment by infocortex** [comment]
fixed in #119
