### ISSUE TITLE
UI problems (single image delete and lack of multi-image operations)

### ISSUE THREAD

**Issue by satra** [NeuroVault/NeuroVault#120]
after deletion of a single image, the redirect should go back to the collection.

it would be nice to be able to select and delete a set of images without deleting the collection. 

in general it would be nice to operate on a selection of images. e.g.,:

- adding tags
- multi image viewing
- deleting
- set decode (@tyarkoni and i spoke briefly about this).

**Comment by chrisfilo** [comment]
multi image operations are now supported by the spreadsheet functionality (edit images metadada from collecitons view).
