### ISSUE TITLE
paginate /api/images

### ISSUE THREAD

**Issue by tyarkoni** [NeuroVault/NeuroVault#122]
There are now enough images that requesting /api/images takes a while to return data (~1 minute). Can we paginate this so that only the first 100 results are returned by default, and then the user has to pass a paging key for subsequent images?

**Comment by chrisfilo** [comment]
Sure - this should be easy: http://www.django-rest-framework.org/api-guide/pagination/

I'm just wondering - why would this be a big deal in an API? Is the concern that the transfer can be interrupted?

**Comment by tyarkoni** [comment]
That's one possibility, but more generally, it will just keep the app responsive. If it takes a minute to serve 1,000 images, it'll probably take 10 minutes to serve 10,000, and I don't think it's reasonable to take 10 minutes to respond to a request. In applications people might not need more than a few images (e.g., maybe I just want to grab a sample to test something out), and making them wait minutes seems unreasonable. Plus it will help keep load and bandwidth down on the server (may not be an issue now, but could be later).

I think it's a good idea to keep the option of retrieving everything in one shot for people who really want it, but that could be done by setting the MAX_PAGINATE_BY value very high, and making the default something like 100.
