### ISSUE TITLE
Image comparison needs more tests

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#133]
The results I see seem unlikely (when comparing the r score to the scatter plot). This might be due to other bugs, but none the less we need tests on simulated data (when we know what correlation to expect) for the comparison methods.

**Comment by vsoch** [comment]
Could you link an example?

And wow, take a look at what happens with an [atlas comparison!](http://neurovault.org/images/compare/1590/1396)

**Comment by chrisfilo** [comment]
For example this one: http://neurovault.org/images/compare/1590/457 is supposed to be r=0.49 over the whole brain, yet none of the regional correlations are higher than 0.3.

What we need are tests where we know the ground truth.

1. Generate data with known correlation
2. Create fake nii objects out of the data
3. Feed it to your routines and check if they return the same correlation value

Similar procedure should be applied to testing if the masking functions work correctly.

**Comment by vsoch** [comment]
I agree.

**Comment by nicholst** [comment]
Love the comparison page!  Especially breaking down by region.

*But* you've got overplotting from hell.  Not sure what to suggest, but one
thing would be that when you hover over the label, show an ellipse
(corresponding to the 95% area of a 2D Gaussian with that region's means,
variance and correlation).

Can help with the stats if needed (key - use connection to a chi^2)...

On Mon, Feb 16, 2015 at 6:18 AM, Chris Filo Gorgolewski <
notifications@github.com> wrote:

> For example this one: http://neurovault.org/images/compare/1590/457 is
> supposed to be r=0.49 over the whole brain, yet none of the regional
> correlations are higher than 0.3.
>
> What we need are tests where we know the ground truth.
>
>    1. Generate data with known correlation
>    2. Create fake nii objects out of the data
>    3. Feed it to your routines and check if they return the same
>    correlation value
>
> Similar procedure should be applied to testing if the masking functions
> work correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NeuroVault/NeuroVault/issues/133#issuecomment-74464393>
> .
>



-- 
__________________________________________________________
Thomas Nichols, PhD
Professor, Head of Neuroimaging Statistics
Department of Statistics & Warwick Manufacturing Group
University of Warwick, Coventry  CV4 7AL, United Kingdom

Web: http://warwick.ac.uk/tenichols
Email: t.e.nichols@warwick.ac.uk
Phone, Stats: +44 24761 51086, WMG: +44 24761 50752
Fax:  +44 24 7652 4532

**Comment by chrisfilo** [comment]
Another one: http://neurovault.org/images/compare/2880/1248 r == 0.63 but the scatterplot does not support that

**Comment by vsoch** [comment]
I think it's an artifact of calculating the global correlation with all values, but then just regions... will test this weekend!

@nicholst - will also deal with overplotting from hell :smiling_imp:

**Comment by tyarkoni** [comment]
Yeah I can see this being right, and just a matter of different correlations at different scales.

Actually one thing this points to that might be really interesting is to formalize some notion of local vs. global correlations--i.e., maps that are similar at a coarse level across the entire brain (i.e., you happen to have the same general regions active in both) versus maps that might show strong local correlations but not necessarily global ones. Actually, the latter seems very unlikely to happen--but what is probably not uncommon is what we're seeing here, where local correlations are low but global correlations are high. One could arguably even interpret this as a kind of quality metric, in the sense that if you have very noisy images, you could still get a large global correlation, but the fact that local correlations are low might warn you not to try to overinterpret local effects.

Anyway, just something to think about.

**Comment by nicholst** [comment]
Huh... this reminds me of functional connectivity, where people will take a
correlation coefficient and break it down into the contributions from
different frequencies, with a spectral correlation.  The difference there,
though, is that the Fourier/spectral decomposition is orthogonal, and so
the sum of the variance explained by each frequency adds to the total
variance explained.

As means within regions, and the data within regions are not orthogonal, we
would have such an additive solution, but it's still worth considering...
but also with the orthogonalisation.

Now, in English:  Consider 3 comparison metrics:  One based on full image
data; One based on a reduced data set, the intra-ROI-means for for some ROI
atlas, and One based on full image data *after* mean-centering each ROI.

The last one will tell you if the *intra* ROI behaviour is consistent
regardless of large scale patterns.

On Fri, Mar 6, 2015 at 7:19 PM, Tal Yarkoni <notifications@github.com>
wrote:

> Yeah I can see this being right, and just a matter of different
> correlations at different scales.
>
> Actually one thing this points to that might be really interesting is to
> formalize some notion of local vs. global correlations--i.e., maps that are
> similar at a coarse level across the entire brain (i.e., you happen to have
> the same general regions active in both) versus maps that might show strong
> local correlations but not necessarily global ones. Actually, the latter
> seems very unlikely to happen--but what is probably not uncommon is what
> we're seeing here, where local correlations are low but global correlations
> are high. One could arguably even interpret this as a kind of quality
> metric, in the sense that if you have very noisy images, you could still
> get a large global correlation, but the fact that local correlations are
> low might warn you not to try to overinterpret local effects.
>
> Anyway, just something to think about.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NeuroVault/NeuroVault/issues/133#issuecomment-77618633>
> .
>



-- 
__________________________________________________________
Thomas Nichols, PhD
Professor, Head of Neuroimaging Statistics
Department of Statistics & Warwick Manufacturing Group
University of Warwick, Coventry  CV4 7AL, United Kingdom

Web: http://warwick.ac.uk/tenichols
Email: t.e.nichols@warwick.ac.uk
Tel, Stats: +44 24761 51086, WMG: +44 24761 50752
Fx,  +44 24 7652 4532
