### ISSUE TITLE
Warning for thresholded images

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#134]
We need to add warning if image seems to be thresholded. This should appear on find similar and comparison pages. We should also consider excluding thresholded maps from find similar page (or make it optional).

**Comment by vsoch** [comment]
My thinking is that this should be a calculation done at initial upload (or update), so it's easy to query and get a Boolean for the map at multiple places in the site, because it would be very intensive (and redundant) to calculate every time that we need it. We should have a consistent visual warning (for example, a symbol or some kind of red box/text with help text) that the user learns to associate with the thresholded maps.  If we were to integrate it as a tag (meaning appearing as a filter in the list of Z, F, other, images still processing) then the user could very easily select only thresholded maps.

**Comment by chrisfilo** [comment]
I agree. The results of the QA procedure (is it thresholded? is it in MNI?) should be stored in the database as image field and exposed via the API. This issue is related to #154.

**Comment by chrisfilo** [comment]
Thresholded images should be excluded from "find_similar" pages. There also should we a warning on the "compare" page if one of the images is thresholded (for example here: http://neurovault.org/images/compare/8499/6)

**Comment by vsoch** [comment]
I'm running into trouble doing a query to filter down to thresholded. For example:

        comparisons = Comparison.objects.filter(Q(image1=image1) | Q(image2=image1),
                  image1__collection__private=False, 
                  image2__collection__private=False)  

could be modified to be:

        comparisons = Comparison.objects.filter(Q(image1=image1) | Q(image2=image1),
                  image1__is_thresholded=False, 
                  image2__is_thresholded=False)  

It's telling me "is_thresholded" is an invalid lookup: 

     TypeError: Related Field got invalid lookup: is_thresholded

I've been looking for specific examples online that might work, but nothing so far!

**Comment by chrisfilo** [comment]
This should not be surprising considering that Comparison fields image1 and
image2 are of type Image which does not have is+thresholded field. You
should either change it to Base StatisticMap (but I'm not sure if this is
possible since this is an abstract field) or filter fields based on their
type after querying.

**Comment by vsoch** [comment]
Oh I see, that's interesting.  Django must look for the field in the model and not in the objects returned that may have inherited fields. I *thought* that I tested for this by checking for the existence of the field in each image:

     comparisons = [comp for comp in comparisons if comp.image1.is_thresholded==False and comp.image2.is_thresholded==False]

(produced no errors!) But Django is smarter that that! I will give this a go with a different model.

**Comment by chrisfilo** [comment]
I think that worked only because all of the comparisons in "comparisons" were on StatisticMaps. Django will cast objects after querying, but you cannot use fields of a particular subclass to query objects. More here: https://django-polymorphic.readthedocs.org/en/latest/
