### ISSUE TITLE
Restrict image comparisons to derivatives of BaseStatisticMap

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#139]

**Comment by vsoch** [comment]
Right now we select based on getting all Images, and then dis-including:

     from neurovault.apps.statmaps.models import Image
     imgs = Image.objects.filter(collection__private=False).exclude(pk=pk1)
     comp_qs = imgs.exclude(polymorphic_ctype__model__in=['image','atlas']).order_by('id')

Should we filter in a different way? There is this function to get the class name:

     image.get_real_concrete_instance_class() 
     neurovault.apps.statmaps.models.StatisticMap

There is also this field to get the map model:

     image.polymorphic_ctype.model
     u'statisticmap'

I don't see any kind of ID for a BaseStatisticMap, so I think I need some help about how to do this restriction. I'm fairly confident that we can fix this just by editing [this line](https://github.com/vsoch/NeuroVault/blob/update/image_comparison/neurovault/apps/statmaps/tasks.py#L101).

**Comment by chrisfilo** [comment]
I agree it's not pretty, but I don't see a different way right now.
