### ISSUE TITLE
provide links to api queries on image and atlas pages. would this be useful?

### ISSUE THREAD

**Issue by jbwexler** [NeuroVault/NeuroVault#151]

**Comment by vsoch** [comment]
API query links would most definitely encourage people to use (or minimally know about) the API - similar to how the Cognitive Atlas has a quick export of a data structure on the individual concept / contrast (etc.) pages. In terms of "useful" - probably someone who is "really" using the API wouldn't go at it on a page by page basis.  So I say useful for analysis, probably not. Useful for incentive / awareness "hey look NeuroVault has an API" - I say yes.

**Comment by chrisfilo** [comment]
We are getting a new page about the API and it is mentioned in the FAQ. Most people benefiting from an API will be looking for it. For others there is the download button.
