### ISSUE TITLE
Define collection sets, download meta info

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#166]
Users should be able to add custom groups of public maps to sets, save sets, share sets, and export the table with set info easily. The API has download functionality, but possibly users would prefer to zip up a set and download from the web portal. Ideally, we could offer some kinds of simple analysis functions directly in the browser, but for now the old fashioned "download and process locally" might make most sense.

**Comment by chrisfilo** [comment]
I think @tyarkoni is working on adding this to neurosynth.
