### ISSUE TITLE
Option to apply same settings to all images in collection

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#171]
From: https://neurovault.uservoice.com/forums/210717-general/suggestions/7189722-option-to-apply-same-settings-to-all-images-in-col (and also @GaelVaroquaux )

When having many images in a collection (e.g. uploaded from folder) it would be easier to have an option to set all images to same Map type/ Modality / Cognitive Paradigm.

**Comment by tyarkoni** [comment]
Per discussion in #234, one approach that would solve this problem would be to have a separate ImageMetadata class that can be attached to both Images and Collections, with the latter case serving as the default for all images. Then there could be an "apply to all" button at the Collection level that overwrites individual image metadata records.
