### ISSUE TITLE
Bug when uploading many images from folder

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#183]
I haven't figured out what is causing this, but when I upload many image in a folder (and this happened previously when I was uploading HCP maps), it only uploads a partial set of the total, and then I have to add the others again. Now that we have brain glass image generation and score generation, this would mean the images and transformations do not get calculated either (as just happened for me). When I upload a smaller number, everything seems to work ok. This could be why there is weirdness with the image counter, if there are images in the database that were uploaded in this fashion that didn't get their pearson scores calculated.

**Comment by chrisfilo** [comment]
Could you provide a zip file of nifti files to replicate this bug?

**Comment by vsoch** [comment]
[zip file](http://www.vbmis.com/bmi/share/chris/data/group_maps.zip)

For the folder zipped above, it stopped at 24 for me, and this is on vagrant but the first time I noticed was for neurovault.org.  I think I know what might be the issue - when I look in the image_data folder, there are 24 brain maps but only 23 brain glass images. I suspect the upload stops if there is an error along the way, even if there is no obvious notification.  I say this because once I was uploading two images, and it stopped after only uploading one, and there were no brain glass images or pickle transforms.  I looked at the script and saw that I forgot to import the function for the task, which means that the upload must have started, stopped/caught the error, and then nothing happened beyond that.
 
[bug](http://www.vbmis.com/bmi/share/chris/data/bug.png)

**Comment by vsoch** [comment]
left shows vagrant, right is image collection folder with only 23 glass brains, bottom right is the celery jobs stopping at glass brain (should have transformation calculations then image comparisons as the last tasks done)

**Comment by chrisfilo** [comment]
And there are not errors in vagrant log? The celery queue is empty? This is so weird. Should the celery cob be initiated during the save() of the statmap object?

**Comment by vsoch** [comment]
Where is the vagrant log? I think that would be the best option to debug!

We can't put the celery job to run within the save() of one map because we have to set up a dependency that has all the new image pks - all the transforms need to be calculated before any pearson correlations are calculated, otherwise we get errors for pretty much every one.

**Comment by vsoch** [comment]
It looks like I can do vagrant up with a [debug option](http://docs.vagrantup.com/v2/other/debugging.html), let me try that.

**Comment by chrisfilo** [comment]
The log is at /var/log/neurovault-tasks/celery.log

**Comment by vsoch** [comment]
The celery jobs were never called because of an error in the upload, so there wouldn't be an error in that log. If there was a celery error I'd see it immediately in my terminal window because I am running the server manually (and I see all the errors when they happen).

**Comment by vsoch** [comment]
I tested this manually this morning, and when running in the manage.py shell, the [portion of the script](https://github.com/vsoch/NeuroVault/blob/update/image_comparison/neurovault/apps/statmaps/views.py#L421) to save all the niftiFiles as new image object worked for all images in my set (all tasks were generated and run successfully).  Could it be some kind of timeout in the browser? It always seems to happen about halfway through the images, given that there is a large set. It also could be something else in the try loop (the [portion about atlases that I did not test](https://github.com/vsoch/NeuroVault/blob/update/image_comparison/neurovault/apps/statmaps/views.py#L388)) that breaks the loop.  I tried to figure out if we had access to [these messages](https://github.com/vsoch/NeuroVault/blob/update/image_comparison/neurovault/apps/statmaps/views.py#L480) but it looks like something that is saved for [rendering for the user](https://docs.djangoproject.com/en/1.7/ref/contrib/messages/#displaying-messages)? I'm guessing this would be a browser pop-up or something if there was an error message, but I did not see one.

Some ideas:

 - possibly more levels of error handling for the function - break the different image types into separate blocks to catch different errors
 - output more debugging at each step (where is the best place for this?)

**Comment by jbwexler** [comment]
I was able to replicate this error when using http://192.168.33.10/ but when I try it on http://192.168.33.10:8080/ it works fine. Not sure what this means...

**Comment by chrisfilo** [comment]
Interesting - I agree that error reporting in the upload_folder function
needs to be improved so it would not fail silently. It's weird that it
works on the django server but fails on nginx/uwsgi. It's worth looking at
the logs as well as nginx config. There is an upload limit, but a) it
should throw a server error b) it should be set to 1000MB.

**Comment by ljchang** [comment]
I'm also struggling to upload a very large dataset (~5000 files, ~6gb). 

Here are a couple of things I've found so far.

1) zipped folders seem to work, but not tar.gz files created using the Python tarfile module. Working for about 30 files at a time.  Haven't found the max limit yet.
2) Sometimes the browser (chrome) crashes when trying to upload a folder with too many files.  Haven't found a reliable maximum number yet.
3) Similar to Vanessa, only a few files appear when uploading a folder with a lot of files.  Haven't been able to find the max number, but it definitely happens around 100 files.

**Comment by ljchang** [comment]
Here is a link to download some of the files I've been having issues with.

https://www.dropbox.com/s/creiofjrz09zxfl/FilesForChris.zip?dl=0

**Comment by chrisfilo** [comment]
I have found and hopefully fixed the tar.gz problem (you can give it a try).

In terms of uploading 6GB of data - our server (nginx) has a limit on how much it can take at once. It's there so we would not get killed by huge requests. That limit is currently set to 1024M. However, such requests should end up with a different error then I'm seeing. What is more the mysteriously missing files issue happen for uploads smaller than 1GB. We need to get to the bottom of this.

We also need to add an upload API so yo would not depend on a browser...

**Comment by ljchang** [comment]
An upload API would be awesome.  We could talk to Anton about possibly adding that functionality.

Also, it seems like I can only upload zipped files with about 150 files inside.  When I've tried 2-300, NV doesn't complete adding all files when they are being unzipped and I get a server error.

**Comment by ljchang** [comment]
I've uploaded about 75% of my large dataset, but at ~3900 image (out of ~6000) I'm now having difficulty interacting with the collection. 

1) I'm frequently getting 502 Bad Gateway errors when interacting with the collection via the web interface
2) I'm having trouble adding more data via the file uploader
3) I'm getting request errors when I try to query the collection via the API (HTTPError: HTTP Error 502: Bad Gateway).  

Is this just too big for Neurovault at this point?  

I was going to keep the collection private until I finished uploading all of the data, but here is the key if anyone else wants to play around (GLSHLWFE).

**Comment by chrisfilo** [comment]
For the record - here's the uwsgi error corresponding to the 502:

	neurovault.org [pid: 24059|app: 0|req: 11/32] 171.66.208.5 () {40 vars in 1094 bytes} [Wed Apr  8 23:49:44 2015] GET /collections/GLSHLWFE => generated 0 bytes in 3 msecs (HTTP/1.1 301) 2 headers in 129 bytes (1 switches on core 4)
	Wed Apr  8 23:50:05 2015 - *** HARAKIRI ON WORKER 5 (pid: 23852, try: 1) ***
	Wed Apr  8 23:50:05 2015 - HARAKIRI: -- syscall> 202 0x701888 0x80 0x2 0x0 0x701888 0x6f742079746c6179 0x7fffaad02118 0x7f1764112f2c
	Wed Apr  8 23:50:05 2015 - HARAKIRI: -- wchan> futex_wait_queue_me
	Wed Apr  8 23:50:05 2015 - HARAKIRI !!! worker 5 status !!!
	Wed Apr  8 23:50:05 2015 - HARAKIRI [core 1] 171.66.208.5 - GET /collections/GLSHLWFE/ since 1428529784
	Wed Apr  8 23:50:05 2015 - HARAKIRI !!! end of worker 5 status !!!
	Wed Apr  8 23:50:06 2015 - DAMN ! worker 5 (pid: 23852) died, killed by signal 9 :( trying respawn ...
	Wed Apr  8 23:50:06 2015 - Respawned uWSGI worker 5 (new pid: 24115)

**Comment by chrisfilo** [comment]
Is there a reason why you want 6000 images in one collection?

**Comment by ljchang** [comment]
I was hoping to share single trial data for every IAPS image for a 182 person dataset.  I don't 'need' to share all 6000 images, but I think it could be a useful resource for anyone who wants run secondary analyses based on any question they might have about viewing affective images.  I'm thinking it might be better at this point to reduce the data on the affective dimension (would reduce the number of images by about a factor of 6).  However, this would prevent others from using the data to answer other questions (e.g., spatial frequency, or specific image content).  It also doesn't have to be in the same collection.  I could upload the ~30 images per subject as separate collections as well.  

The broader idea was to use this dataset as an example for the meta-data extension.

I must admit that I didn't really spend much time considering the scale of this dataset.

**Comment by chrisfilo** [comment]
I managed to query your collection through ./manage.py shell and it was
very quick. I think the bottle neck is generating the HTML not the
database. I try to increase the harakiri timeout.

**Comment by chrisfilo** [comment]
Increasing the timeout did the trick. Nonetheless generating json representation of your collection takes 35 seconds and the resulting JSON file has 2.7mb: http://neurovault.org/api/collections/GLSHLWFE/?format=json. Maybe you guys can look into trying to optimize this.

**Comment by tyarkoni** [comment]
DataTables can handle server-side pagination quite easily. The API just
needs to be modified to handle the DataTables-specific query parameters. I
don't think there's any reason to serve all images at once; we should
probably default to 100 hits at a time. I'll take a look at it tonight if I
have time.

**Comment by ljchang** [comment]
Awesome, increasing the timeout helped a lot.  All of the images are uploaded now and have been moved from private to public. I'll add the meta-data whenever that functionality gets deployed.

**Comment by chrisfilo** [comment]
That would be great @tyarkoni! I think it also might be worth profiling/optimizing the API: http://www.dabapps.com/blog/api-performance-profiling-django-rest-framework/

**Comment by chrisfilo** [comment]
@vsoch added pagination to the API - we just need to update the frontend #83

**Comment by satra** [comment]
@chrisfilo - i'm running into similar issues here - where uploading a zip file crashes with any error reporting (i have long names for each file). and uploading folders results in a very small subset actually being uploaded (1 out of 377 in one case, and 65 out of 206 in the other). i'm trying to upload to a private collection.

**Comment by chrisfilo** [comment]
Our logs indicate that your crash is related to #202. Immediate workaround involves making sure the names of files are shorter than 100 characters.
