### ISSUE TITLE
Collections API should not return all image in a collection

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#222]
The API currently returns a list of images associated with a collection, and this is not a reasonable thing to do as the collection with 6000 images will time out for a single query, eg:

      http://neurovault.org/api/collections/?format=json&limit=1&offset=157

I put the link in a code box because you should not click it :)

The user should need to retrieve the collection first, and then get the images with the image api (paginated) based on the collection.

**Comment by chrisfilo** [comment]
Let's have a paginated /api/collections/157/ images path to retrieve all
images from a given collection.

**Comment by vsoch** [comment]
good idea.
