### ISSUE TITLE
Bug When Editing Single Image

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#230]
I've seen this once before- when I edit an image (the single view) the collection field goes away, and there is nothing to select:

![bug](https://cloud.githubusercontent.com/assets/814322/7396263/b3749834-ee54-11e4-9342-13da8dcbe851.png)

This is for a thresholded map, if that might be meaningful!

**Comment by chrisfilo** [comment]
This applies to superusers only. We need to fix this before you move on.

**Comment by vsoch** [comment]
holy cow, you are fast! Yes, we do need to fix. For the instance I am working on, the user has uploaded an unthresholded map, but it's a different image.
