### ISSUE TITLE
Add analysis_level field and modify map_type to accommodate for new map types

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#263]
To accommodate @ljchang use cases I propose the following:

* add three new types to choose from for map_type: "weight/beta map", "ROI/mask", "parcellation"
* add a new field for BaseStatisticalMap - "analysis_level" - with the following options: "single-subject", "group", "meta-analysis", "other"

neuro-learn website could look for "weight/beta" maps as for decoding purposes and filter the analysis level. Additionally we will set map_type to ROI or parcellation automatically when user upload maps in bulk (see #261).

**Comment by chrisfilo** [comment]
@ljchang what is a "single subject pattern map"?

**Comment by ljchang** [comment]
A predictive weight map that is trained to predict data from a single subject.  This could be in contrast to a  predicted weight map that is trained on many subjects ("group") to predict a new subject.
