### ISSUE TITLE
Previously passing builds are not passing on Travis

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#265]
It is related to the function "testFEAT_NIDM" in test_feat.py.  Specifically, the error is that "export_dir" is not defined, and that is likely because something is failing in this block (either the try, or the if statement):

        for fname, info in self.testfiles.items():
            info['found_feat'] = False
            for root, dirs, files in os.walk(info['dir']):
                if detect_feat_directory(root):
                    print 'Found FEAT directory at {}.'.format(root)
                    info['found_feat'] = True
                    try:
                        fslnidm = FSLtoNIDMExporter(feat_dir=root, version="0.2.0")
                        fslnidm.parse()
                        export_dir = fslnidm.export()
                        ttl_file = os.path.join(export_dir,'nidm.ttl')
                    except:
                        print("Unable to parse the FEAT directory: \n{0}.".format(get_traceback()))

The test works locally. I'm going to try debugging using my PR.

**Comment by vsoch** [comment]
I think the error is related to an update to nidm-results:

https://github.com/incf-nidash/nidm-results_fsl/commit/5db7d2ab9b897ed430ba08a86a98af5056293ff3

Looking into this.

**Comment by chrisfilo** [comment]
Most likely. Let's  fix an older revision in requirements for now.

**Comment by vsoch** [comment]
Ok, I'll test on my current PR and do a new one if I find a fix.

**Comment by vsoch** [comment]
How do I choose a commit? I first tried an earlier version of nidmresults, and that failed. The actual failure is coming from nidm_results_fsl however (and I don't know enough about the package to know how that relates to nidmresults). I tried an earlier version of that, but it's not logical that would be the error because the last commit was mid January. I tried earlier versions of both, and then a new error pops up about missing "contrasts" variable. Is there a logical way to choose commits, and for which packages?

**Comment by nicholst** [comment]
@cmaumet, is there any advice we can offer here?  For the record, can you summarise the key changes with NIDM 1.0.0 and the nascent NDIM 1.0.1?

**Comment by vsoch** [comment]
Phew, I found the commit that works!

https://travis-ci.org/NeuroVault/NeuroVault/builds/62968236

I didn't realize that I needed to go well beyond the date that last worked, because the merge included commits from many months back that weren't deployed until the merge was official.

I will submit a PR asap, just going to brush my teeth first.

**Comment by cmaumet** [comment]
Hi @vsoch, @chrisfilo: Sorry about that, I had in mind that NeuroVault was relying on a fix branch (but that's only true for nidm-results_fsl)...

There have been a lot of changes in NIDM-Results 1.0.0 compared to 0.2.0, let me have a look and write a recap and we can then go back to the tests and make sure they still pass with this new version?

**Comment by vsoch** [comment]
Ok, sounds good. The test that was failing [is here](https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/apps/statmaps/tests/test_feat.py#L93) and specifically, the function from fslnidm is:

      from nidmfsl.fsl_exporter.fsl_exporter import FSLtoNIDMExporter

I don't know the whole story, but it looks like we are using [a branch from infocortex](https://github.com/NeuroVault/NeuroVault/blob/master/requirements.txt#L44) with customizations for our test data, and there was [discussion of merging](https://github.com/incf-nidash/nidm-results_fsl/pull/32)? I think the ideal would be to have some merge, and then be able to use the master branches (with any tweaks to the current NeuroVault code that are necessary.)  Please let us know the changes so we might make the most up to date versions work with the NeuroVault code base! :space_invader:
