### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#286]
Should time zone be set to "Europe/Berlin?"

https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/settings.py#L43

It probably doesn't matter because we don't do any kind of billing, but it says that there can be errors with daylight savings and the like:

https://docs.djangoproject.com/en/1.8/topics/i18n/timezones/

so maybe it would be safe to use UTC.

**Comment by souravsingh** [comment]
Should the time zone settings be changed? If so, This can be a quick PR.

**Comment by vsoch** [comment]
I don't think this is an important issue at the moment, as we don't have any kind of functions internally or for users that depend on time.

**Comment by souravsingh** [comment]
I think Issue #250 might require a function that depends on time,since we wish to display the collections that were uploaded first.
