### ISSUE TITLE
Renaming collection

### ISSUE THREAD

**Issue by schwarty** [NeuroVault/NeuroVault#289]
Would be great if we could rename a collection after it has been created.

**Comment by chrisfilo** [comment]
This is possible when you press "Edit collection".

**Comment by schwarty** [comment]
I know, but it does not work.

**Comment by chrisfilo** [comment]
Ah I think I know what's going on. Does this collection have a doi of a
corresponding paper? Then the name will be always set to the title of the
paper since it's a one to one relationship. Does this conflict with your
use case?
