### ISSUE TITLE
Dockerize neurovault

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#291]
* https://www.calazan.com/using-docker-and-docker-compose-for-local-django-development-replacing-virtualenv/
* https://github.com/jcalazan/docker-django-local

migrate tests to use docker images:
* https://github.com/moul/travis-docker

**Comment by vsoch** [comment]
yes yes yes yes this is awesome! :ship:

**Comment by vsoch** [comment]
I can offer to test, etc.

**Comment by vsoch** [comment]
Pre-generated atlas pickle is missing for scatterplot:  /code/neurovault/static/atlas/atlas_mni_4mm.pkl
