### ISSUE TITLE
Unique Images Names in Metadata

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#321]
I am trying this out for the first time, and I get an error about unique image names:

![screenshot from 2015-08-16 05 02 28](https://cloud.githubusercontent.com/assets/814322/9293153/19111f1c-43d4-11e5-95a8-56255959f30d.png)

I understand the want for unique filenames, but unique image names seems problematic given that many might upload images of the same filename from different folders (eg, "func.nii.gz"), which will be turned into unique image names. I'm sure this was talked about before, but I wanted to bring it up in case not. What is the rationale?

**Comment by chrisfilo** [comment]
Thanks for spotting this. This is a bug which we should fix - I opened an issue for it #322.

I would not get too attached to filenames - we use them for internal storage and we rename files when the names clash. The actual "Name" property of image is the important one. The reasoning behind making it unique within a collection was to enforce some kind of an order (having multiple maps with the same name is confusing).

**Comment by vsoch** [comment]
great, thanks! I agree about the naming convention, that's a good point I didn't think about.

**Comment by chrisfilo** [comment]
I was thinking a bit more about this, and maybe the current behaviour is actually good. It allows people to quickly "dump" data and it will take whatever they will throw into NeuroVault (including files with the same names). However if the user wants to edit the file metadata (either through single map edit dialog or the tabular interface) all of the constraints will be enforced.

It might be worthwhile instead of enforcing checking the name constraint during bulk upload we should have a warning message on the collection and image level that would warn users that their images have missing metadata and/or invalid names. We can block some features (neurosynth decoding, similar map search, 3D viewer) until those problems are resolved to force more people to fill in metadata.

**Comment by vsoch** [comment]
As long as there is a warning, that seems reasonable. As a user I would be annoyed if I uploaded say, 6000 maps, and then was told the names must be unique. Actually, the spreadsheet would be helpful because I could copy paste the new names, which is easier than manually changing them one by one, or renaming the files. So possibly the warning wouldn't be so useful in that, for the extreme cases, the user wouldn't likely change his or her behavior / file naming before uploading.

This also has me thinking that, along with the option to select multiple images to delete, we generally need more sophisticated filters and operations on images. For example, I should be able to select a button (or something) to quickly filter down to images with/without contrasts, with/without unique names, etc. Getting that kind of nice functionality in an interface (and not having it be clunky and confusing) will be a challenge. Further, however that work for a single collection table, that's the same kind of search/filter that we need for the entirety of NeuroVault.  And it probably should be integrated into the "find_similar" interface, because having multiple places to search is confusing. I think step 1 is figuring out something reasonable for the individual collections, but doing so in mind of possibly extending it to all images!

Search and filtering, specifically for such large data, is hard, or at least I don't feel that I know much about how to do it right. Our current "find similar" uses Django's internal database querying functions, and then renders the top 100 with a pybraincompare interface. This kind of solution would be reasonable for a small or local application, but it's not going to scale. It is static and inefficient. I / we / NeuroVault family need to think about a more scalable search strategy, and browse around to see what kind of solutions other people have come up with. This strategy should be able to handle searching based on similarity scores (those that are existing and those that have yet to be developed), as well as meta-data for images and collections. Everyone and their three-toothed cousin uses Django, so I'm sure there are good solutions!

**Comment by chrisfilo** [comment]
The filtering is an important but separate issue. I think we should start small with improving the find similar view (see #143). From a technical point of view I think all the queries should be done server side and exposed to the view via AJAX.
