### ISSUE TITLE
DOI of Papers Links to Abstracts

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#326]
It will be an issue for the url of a paper to go the abstract, as annotations are best (and likely done) on the full text. We will have a hard time getting them given the abstract links, so we should make sure they go to full text from the getgo!

**Comment by chrisfilo** [comment]
I don't think this is something we can resolve. The links set to whatever the DOI resolver gave us which is provided by the publisher. It is up to the publisher to show you either the abstract or full text.

For example plos is pointing to full text: http://doi.crossref.org/servlet/query?pid=k.j.gorgolewski@sms.ed.ac.uk&format=unixref&id=10.1371/journal.pone.0097176

**Comment by vsoch** [comment]
Interesting, it does seem to vary!

We will need a more clever solution than just following a single link, because we would want to grab an annotation from any and all versions of an article out there (pubmed, sciencedirect, journal, etc.).  I'll think more about this.

**Comment by chrisfilo** [comment]
I'm closing this since there is nothing we can do about what we get from crossref.
