### ISSUE TITLE
Contrast names "accept" and "reject" for BART instantiation

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#333]
This image from the BART task should be changed to "cash average" http://neurovault.org/images/463/ instead of "accept," as (I think) we are describing the same thing in two places, and "cash average" is more specific (and defined in the cognitive atlas). The same (I think) is true for reject: http://neurovault.org/images/459/ this condition should be called "pumps average" as it is the case when the person pumps he/she is rejecting the cash.

If we enforce the unique IDs from the cognitive atlas to define the contrasts, this should be resolved, and I can fix this when I re-tag all of the images.

**Comment by vsoch** [comment]
"explode" should also be called "explode average"

**Comment by vsoch** [comment]
Fixed.

**Comment by chrisfilo** [comment]
thanks!
