### ISSUE TITLE
Cannot edit image details

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#334]
To reproduce:

- Go to collection, click on an image
- Click "edit details"
- Try changing anything and click submit
- The error message will say that an image already exists

>> An object with this name already exists in this collection.

**Comment by vsoch** [comment]
Rescope this bug - we should have a fix to rename images that are uploaded with the same names.

**Comment by chrisfilo** [comment]
Images with the same name are now allowed.
