### ISSUE TITLE
Images in the collection view should be sorted by ID not View by default

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#341]

**Comment by vsoch** [comment]
That is pretty easy to do - it just means changing the query to retrieve them.  what is the rationale though? Why is it a bug?

**Comment by chrisfilo** [comment]
I would prefer to do this in jquery tables rather than django (so it would be clear in the interface which column is using for sorting). The problem is that when people add images to existing collection the order in which they are display changes which is confusing. This suggestion comes from a user.

**Comment by vsoch** [comment]
ascending or descending?

**Comment by vsoch** [comment]
If you don't want order to change, I would suggest ascending, since new images will have larger IDs.

**Comment by chrisfilo** [comment]
yes that would be optimal!

**Comment by vsoch** [comment]
done!
