### ISSUE TITLE
Make lists of fields a bit longer

### ISSUE THREAD

**Issue by GaelVaroquaux** [NeuroVault/NeuroVault#352]
It seems that fields are by default limited to listing 10 entries. In many situations, a longer list by default would require less clicks from the user. I have in mind in particular images, as in
http://neurovault.org/images/10480/
or the collection page
http://neurovault.org/collections/16/

For these (and maybe others), I would suggest defaulting to 25 entries in the list.

**Comment by souravsingh** [comment]
I would like to work on the issue.How do I start?

**Comment by chrisfilo** [comment]
The only problem I have with longer list of images on the collection view is that it will make the view asymmetrical (height of the Papaya viewer will be shorter than list of images). Any ideas how to make it look better? @erramuzpe

**Comment by erramuzpe** [comment]
Yes, I realized about that (that's the reason why it was 7 by default). I don't know what to say, not really a design expert :) I would sacrifice the design in favor of usability until something is figured out.

**Comment by chrisfilo** [comment]
Yes let's do that (7 with viewer, 25 without).
