### ISSUE TITLE
List NIDM files instead of statistical maps derived from it on the collection view

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#372]
Now it makes sense since we have the new viewer.

**Comment by vsoch** [comment]
I looked at this, but I'm not sure where the url is specified for the rows. I found that generation of the tables has moved to a function within views:

https://github.com/vsoch/NeuroVault/blob/enh/nidm-viewer/neurovault/apps/statmaps/views.py#L966

but I was not able to trace where the function "row.get_map_type_display() comes from:

https://github.com/vsoch/NeuroVault/blob/enh/nidm-viewer/neurovault/apps/statmaps/views.py#L984

or even what a "row" is an instance of. I thought it was an image object, but I can't find that function in models.py. I'll push a PR without this change for now.

**Comment by chrisfilo** [comment]
Yes we switched to using API to provide data for datatables using this extensions: https://bitbucket.org/pigletto/django-datatables-view.

The "row" is an item from the list returned by the queryset defined here: https://github.com/vsoch/NeuroVault/blob/enh/nidm-viewer/neurovault/apps/statmaps/views.py#L970

I was trying to implement this the other day, but I run into problems when a collection has both NIDM and normal statmaps (concatenating querysets does not work, serializing them will disable server side search and paging).
