### ISSUE TITLE
Proposed: Disable interpolation (smoothing) in papaya by default

### ISSUE THREAD

**Issue by nicholst** [NeuroVault/NeuroVault#380]
Not sure how people feel, but I think it is essential that smoothing of stat maps is *not* done by default... the finite resolution of statistic maps should be plainly obvious (not to mention that blurring of a thresholded *anything* is just mugly).  As an added bonus it should be that much faster (though I can't tell a difference in the few images I played with).

**Comment by chrisfilo** [comment]
+1
