### ISSUE TITLE
Image reports "nan% of meaningful voxels are outside of the brain"

### ISSUE THREAD

**Issue by bcipolli** [NeuroVault/NeuroVault#382]
http://neurovault.org/images/12137/
Note: When I download and check the image, all voxels are zero.

Two issues:
1. Image reports "nan% of meaningful voxels are outside of the brain"
![image](https://cloud.githubusercontent.com/assets/4072455/11184980/4e4a7888-8c2f-11e5-9bcd-597856a47858.png)
2. This image also causes a script error:
![image](https://cloud.githubusercontent.com/assets/4072455/11184913/0878f762-8c2f-11e5-8c2d-470a27263d0b.png)

Expectation:
The interface should be robust enough to deal with invalid images.

**Comment by bcipolli** [comment]
Also:
http://neurovault.org/images/10247/

**Comment by chrisfilo** [comment]
Those images are empty!

**Comment by bcipolli** [comment]
>The interface should be robust enough to deal with invalid images.

I know :) But the interface chokes; you can't see the 'details' and it's not clear that that's the issue when looking on the website.

**Comment by bcipolli** [comment]
When does this get pushed to the website so I can verify?

**Comment by chrisfilo** [comment]
I just deployed it. You can test it now.

**Comment by bcipolli** [comment]
Looks great! Thanks!
