### ISSUE TITLE
tried to login via google  -- lead to Server Error (500)

### ISSUE THREAD

**Issue by yarikoptic** [NeuroVault/NeuroVault#389]
just happened 
Fri Dec 18 16:10:21 EST 2015
and was coming from 129.170.31.x network   in case you want to check smth in the logs

not sure what was my previous login and either it was via google, it has been a while ;-)

**Comment by chrisfilo** [comment]
I can replicate Russ. Investigating.

**Comment by chrisfilo** [comment]
Try now.

**Comment by yarikoptic** [comment]
On Fri, 18 Dec 2015, Chris Filo Gorgolewski wrote:

> Try now.

works! thanks
