### ISSUE TITLE
is_thresholded is not set

### ISSUE THREAD

**Issue by bcipolli** [NeuroVault/NeuroVault#397]
Over 6000 images I've downloaded, none have `is_thresholded=True`. This, despite some of them being pretty obviously thresholded, e.g.
http://neurovault.org/images/3821/

Is there a good work-around for this, or is it something that could be fixed quickly? I'd like to eliminate thresholded images from my dataset.

**Comment by chrisfilo** [comment]
The image you point to (http://neurovault.org/images/3821/) is not thresholded (just lower the threshold in papaya) and is_thresholded is not set to True (which is correct). I think the heuristic for thresholding detection actually worked well here.

**Comment by bcipolli** [comment]
I see. And I'm not being careful enough, sorry; I forgot that I already had a filter set up, upstream. I need to take my time when opening these issues :-1: 

I opened an issue re: papaya above, as the default map views are quite different between papaya and pycortex.
