### ISSUE TITLE
No way to re-open overlay

### ISSUE THREAD

**Issue by bcipolli** [NeuroVault/NeuroVault#399]
If I press "Close overlay", I can't get it back.
I'd rather have a "hide overlay" that becomes "show overlay" if clicked.
Workaround is rather easy: reload the page.

![image](https://cloud.githubusercontent.com/assets/4072455/12007988/948f867a-abd4-11e5-8846-383af23174e9.png)

**Comment by chrisfilo** [comment]
This would require a change in papaya. You should have look at their
codebase to see how hard this would be.

**Comment by bcipolli** [comment]
:+1: I see. I will look there, open an issue, and cross-ref here.
