### ISSUE TITLE
Migrate to `docker machine`

### ISSUE THREAD

**Issue by bcipolli** [NeuroVault/NeuroVault#403]
When running `boot2docker init`, this is splashed on my screen:
```
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.
```

I will try getting this to work via `boot2docker`, then see if I can't get `Docker Machine` running too.

**Comment by chrisfilo** [comment]
Better start using docker machine. Maybe you could update the readme while
you doing it.

**Comment by bcipolli** [comment]
Yep, if I'm able to do it, I plan to!

**Comment by bcipolli** [comment]
Please sees #404
