### ISSUE TITLE
Add a close account feature to Settings

### ISSUE THREAD

**Issue by burnash** [NeuroVault/NeuroVault#420]
Not the favourite feature of any web-app developer, but:

* It's polite.
* From time to time I create new NeuroVault accounts for manual testing purpose and it'd be great if I have a way to discard these accounts.

**Comment by souravsingh** [comment]
I would like to help in this issue.How do I start?

**Comment by onyekaa** [comment]
Saw this issue in the django group and wondered if you've resolved this...if not. What do you want to happen when an account is closed?

**Comment by chrisfilo** [comment]
This has been closed by #472
