### ISSUE TITLE
Selecting task with no images triggers error

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#444]
To fix this, I'll return a message to the user that no tasks are tagged with the one selected. I was thinking of filtering the list of tasks, but I think the select2 makes it reasonable to keep all of them, and selecting a task and then seeing that there are no tagged images could trigger a user to want to tag!

**Comment by chrisfilo** [comment]
If we can make #441 to work this will not be an issue anymore (since there will be only one search box). Sitemap will should not even expose empty task views for indexing. We can enforce it even more by adding a noindex tag to empty task views.

**Comment by vsoch** [comment]
Agreed, and in the meantime I've added the fix to the PR so we don't trigger errors. Sitemap is done.
