### ISSUE TITLE
How to add sample data?

### ISSUE THREAD

**Issue by iCHAIT** [NeuroVault/NeuroVault#452]
Hi, I was able to setup NeuroVault on my local machine but I cannot figure out how to add sample data to the site, I could not find any command that would do that for me?

**Comment by chrisfilo** [comment]
What I usually do is I create a "test" user and upload a bunch of files from our tests - https://github.com/NeuroVault/NeuroVault/tree/master/neurovault/apps/statmaps/tests/test_data/statmaps

This PR was trying to address this issue in more automatic way #165. This is also related to #85.

It would definitely help to automate this! #165 would be a good starting point.
