### ISSUE TITLE
Uploading thresholded files fails

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#455]
Steps to reproduce:

1. "Add image one by one"
2. Select thresholded image
3. submit
4. Tick the "I know it's thresholded" checkpoint and submit again
5. You get "Binary Block is Wrong size"  error (https://opbeat.com/neurovault/neurovault/errors/155/)

I think this is an interaction of a) converting .nii to .nii.gz during the first submit and b) submit cache mechanism (https://github.com/un1t/django-file-resubmit).

**Comment by avisrivastava254084** [comment]
I would like to go through this bug. Please help me in the following:
1. Setting up the environment
2. Is the backend accessing language(Database Query Language) used is SQL?
Thanks.

**Comment by chrisfilo** [comment]
Start by reproducing the bug. All I could figure out about fixing this bug is already described above.

**Comment by erramuzpe** [comment]
Also, after submitting 1st time: of you tick the "Ignore warning" and if you change the image, and submit, another exception will arise:

_The 'thumbnail' attribute has no file associated with it._

This can be solved checking if a new file was selected, and if so, unselecting or hiding the "Ignore warning" tick. Working on it.

**Comment by chrisfilo** [comment]
Hmm I have not run into the `thumbnail` error. Maybe it's unrelated. Does adding thresholded .nii.gz (not .nii) maps work on your set up? Does adding unthresholded maps work?

**Comment by erramuzpe** [comment]
I get 'Binary block is wrong size' for both nii and nii.gz thresholded. 

It works correctly for both unthresholded ones (if I get rid of my unrelated thumbnail bug deleting the line https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/apps/statmaps/templates/statmaps/_meta_image.html#L4 )

**Comment by chrisfilo** [comment]
I can confirm that it also affect compressed files (which makes it this issue even more severe).
