### ISSUE TITLE
Empty tasks should redirect or prevent indexing in other way

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#458]
Right now empty tasks are listed as "Search" which is misleading.

**Comment by vsoch** [comment]
It's likely they belong to private collections - we don't filter for that here:

https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/api/sitemap.py#L31

but we do for the view

https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/apps/statmaps/views.py#L414

**Comment by chrisfilo** [comment]
Could be - we should exclude private collections.

**Comment by avisrivastava254084** [comment]
Hi Gaffer!
Just sent you a mail. Please go through it, the subject of which is subjected as "Empty tasks should redirect or prevent indexing in other way".
Thanks.

**Comment by chrisfilo** [comment]
Hi @avisrivastava254084! Let's keep the conversation here. Fixing this bug involves the following:

- [ ] Change what is displayed when a task id with no images is requested (such as http://neurovault.org/tasks/trm_55a6a8e81b7f4). It should be simple modification of the normal task page, but with text explaining that there are no maps in neurovault tagged with this task.
- [ ] The page should also have a <meta name="robots" content="noindex"> in the head so it will not show up on google search.

**Comment by avisrivastava254084** [comment]
Dear Sir,
As I have seen #458 has been closed, which one would be better(better for a
Python/Django developer) to contribute to among the following:
1. #455
2. #436
Thanks.

On Wed, Mar 2, 2016 at 6:05 AM, Chris Filo Gorgolewski <
notifications@github.com> wrote:

> Closed #458 <https://github.com/NeuroVault/NeuroVault/issues/458>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NeuroVault/NeuroVault/issues/458#event-573941826>.
>



-- 
Aviral Srivastava
+918004860407

**Comment by chrisfilo** [comment]
#436 has been resolved by a recent merge. #455 is a good candidate.
