### ISSUE TITLE
Move "Number of subjects" field from Collections to StatisticalMaps

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#463]
Also, make it compulsory (unless the map is a parcellation, ROI mask, single subjects or meta-analysis - in those situations the field should be hidden from the form).

@cmaumet @jokedurnez @nicholst

**Comment by cmaumet** [comment]
Great! This is consistent with the work-in-progress PR https://github.com/incf-nidash/nidm/pull/374. Once https://github.com/incf-nidash/nidm/pull/374 is merged, number of subjects per statistic map will be available from NIDM-Results packs.

**Comment by nicholst** [comment]
+1 ...really important, as there are various exclusion / data issues that arise that lead to different stat maps having different number of subjects.
