### ISSUE TITLE
future: will need to discuss integration with neuropower

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#485]
when the @neuropower app is updated, @jokedurnez @chrisfilo let's discuss how to best manage data upload between the two.

**Comment by chrisfilo** [comment]
I think we already discussed this and agreed to go with a similar scheme to
what we are doing for neurosynth (so dedicated page for adding a single map
and redirect back to neuropower). Did something change?

**Comment by vsoch** [comment]
Mostly me needing to get a full picture because I'll likely help implement. Joke and I were chatting on slack, and I wanted to make an issue to get your ear in case we need to discuss details. :)

**Comment by jokedurnez** [comment]
So @chrisfilo, are you ok with the default being not public? (given that this will be pilot data)

**Comment by chrisfilo** [comment]
Yeah I'm fine with that. We should also add a "Neuropower" button on the map view (or even better collapse neurosynth, neuropower, and find similar into one drop down "analysis" button).

Similarly to Neurosynth neuropower would get the id of an uploaded image through a GET call and use the API to figure out remaining metadata. Speaking of which those two issues need to be done to improve metadata description that is useful for neuropower #465 and #463.

**Comment by vsoch** [comment]
I can likely assign myself to all these issues - first I'll do some tweaks to the neuropower app, and then I can get to the NeuroVault metadata description, and then collapsing into an analysis button.

**Comment by chrisfilo** [comment]
Looking forward!
