### ISSUE TITLE
hyperlink error in API root

### ISSUE THREAD

**Issue by erramuzpe** [NeuroVault/NeuroVault#491]
In http://neurovault.org/api/  "collections" links to "my_collections"

` "collections": "http://neurovault.org/api/my_collections/",`

I've trying to solve this, but could not find where it is generated.

**Comment by erramuzpe** [comment]
Must be here .... https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/api/serializers.py

**Comment by chrisfilo** [comment]
Indeed a bit mysterious. Something about the class inheritance?

**Comment by erramuzpe** [comment]
The router we are using in the api.urls is the Default one, which says "automatically generated root view". I don't know where does it take the info to generate the link, but I would understand "collections" to be repeated, cause "my_collections" inherits from it, but not vice versa :thought_balloon:

**Comment by erramuzpe** [comment]
Ok, this is funny... if you put "my_collections" line over "collections", you get a double "collections" link instead of double "my_collections". https://github.com/erramuzpe/NeuroVault/blob/9f86bad03865bb704a42f4e9fd8349a8bf44d919/neurovault/api/urls.py#L8

**Comment by erramuzpe** [comment]
Ok, the answer for this was in the link I pasted the previous day. :sob: 

_There are two mandatory arguments to the register() method:

prefix - The URL prefix to use for this set of routes.
viewset - The viewset class.
Optionally, you may also specify an additional argument:

base_name - The base to use for the URL names that are created. If unset the basename will be automatically generated based on the queryset attribute of the viewset, if it has one. Note that if the viewset does not include a queryset attribute then you must set base_name when registering the viewset._
