### ISSUE TITLE
Something is still wrong with tags

### ISSUE THREAD

**Issue by erramuzpe** [NeuroVault/NeuroVault#505]
I saw an error related to tagging in Opbeat. Made some checks and discovered that when adding new tags, `TAGGIT_CASE_INSENSITIVE=True` is not forcing lowercasing. Thus, KeyTags could be not lowercased. This would not be a problem, since new lowercased/uppercased tags will be linked to the Key with no error. 

The problem comes when adding same tag in the form with different cases, say "brain" and "Brain" at the same time. Both will be saved as KeyTag, and then errors will arise. 

There is [this](https://github.com/shacker/django-taggit) fork that allows ``TAGGIT_FORCE_LOWERCASE = True`` but I'm trying [this solution](http://stackoverflow.com/questions/25676952/override-django-taggit-tags-so-that-they-are-always-lowercase) at form level to avoid this. 
If all tags are lowercased, there is no error possible, since if you try to save "brain" and "brain" at the same time, just 1 KeyTag will be saved.

**Comment by chrisfilo** [comment]
That error was because the migration was not applied (due to my mistake during deployment). Everything should be fine now.
