### ISSUE TITLE
Highlight which map is currently being displayed

### ISSUE THREAD

**Issue by cmaumet** [NeuroVault/NeuroVault#510]
When clicking on the **View** ("eye"-like) buttons in a collection (e.g. http://neurovault.org/collections/16/), the view is updated but the "eye" button list is not updated (e.g. some of the eyes could be hidden) which makes it difficult to understand which map is currently displayed:

Collection 16 - initial view
![image](https://cloud.githubusercontent.com/assets/5374264/15604333/bac18be0-23f7-11e6-9361-36e189fa49ab.png)

Collection 16 - after clicking on the second "eye" (fALFF: Future)
![image](https://cloud.githubusercontent.com/assets/5374264/15604364/e17d13da-23f7-11e6-84dd-735f42cee518.png)

I am using Chrome Version 49.0.2623.112 (64-bit).

Could the map list be updated to highlight the map(s) currently being displayed?

**Comment by chrisfilo** [comment]
From your screenshots and my attempts to replicate this seems that when you click the eye button the map view is updated and the corresponding button **is highlighted**. I don't quite understand the nature of the problem you are reporting. What is the desired behaviour?

**Comment by cmaumet** [comment]
I think I understand now! Is it correct that only one map is always displayed at a time on NeuroVault and that this is the map for which the "eye"-button has a grey background (instead of white)?

I guess I was expecting something more like what is on neurosynth: (e.g. http://neurosynth.org/analyses/terms/pain/) where when a map is not displayed you get a "eye closed" and when the map is displayed you get an "eye open". When I first opened the collection, seeing all the "eye"-buttons being "open", I thought all the maps were displayed, overlaid on top of one another, hence my misunderstanding. 

Feel free to close the issue.

**Comment by chrisfilo** [comment]
Yes - only one map is displayed at the same time and this is reflected by the "eyes".
