### ISSUE TITLE
API: list NIDM-Results packs within a given collection

### ISSUE THREAD

**Issue by cmaumet** [NeuroVault/NeuroVault#511]
Similarly to how we can list images that are part of a collection with 

**/api/collections/{pk}/images**

, would it be possible to list all NIDM-Results packs stored in a given collection with something like 

**/api/collections/{pk}/nidm_results**

? (This could be used in the meta-analysis script of the NIDM-Results paper in preparation.)

**Comment by chrisfilo** [comment]
Actually /api/collections/{pk}/images should list both NIDM Results and statistical maps (basically all types of objects in the collection), but for some reason(non-trivial) this is broken. I'll look into this, but no ETA. You might need to to use http://neurovault.org/api/nidm_results/ for now.

**Comment by erramuzpe** [comment]
/api/collections/{pk}/images works for me in my local. It was not working in neurovault.org 2 mins ago, but now works again.

**Comment by chrisfilo** [comment]
Does it list NIDM Results objects (not just NIDM Results statistical maps) for you?

**Comment by erramuzpe** [comment]
No, just the NIDM Results statistical map. For example, collections/877/ has 33 images (4 are NIDM Results objects). Checking /api/collections/877/images I get just 29

**Comment by chrisfilo** [comment]
But this could be a good way to approach things. @cmaumet why don't you query the /api/collections/{pk}/images and for each image follow the .ttl link to get the metadata you need?

**Comment by cmaumet** [comment]
@chrisfilo: if I had access to the turtle that would be good but I can't see link to the turtle in http://neurovault.org/api/collections/877/images/. Or do you mean replacing the image name by "nidm.tt" to actually retrieve the turtle document?

**Comment by chrisfilo** [comment]
Ah I see - I can add this path easily. For now, just grab "nidm_results" field and append ".ttl"
