### ISSUE TITLE
debug nidm viewer current bug

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#521]
http://neurovault.org/collections/NJXQPEEK/pain_01.nidm

**Comment by vsoch** [comment]
going to leave notes here for documentation - viewer is working locally with current master branch, but this is for the index template, likely the bug is in the embed template.

![image](https://cloud.githubusercontent.com/assets/814322/15871895/9863fd8c-2cab-11e6-9524-5ef4685ea059.png)

**Comment by vsoch** [comment]
error reproduced with embed template locally

![image](https://cloud.githubusercontent.com/assets/814322/15872019/369fe146-2cac-11e6-89b8-ed19ac77a226.png)

**Comment by vsoch** [comment]
ok, for me this bug was related to having multiple installations of nidmviewer - the template for embed being used was an old one. When I did 

      pip uninstall nidmviewer

multiple times, reinstalled, and ran, I now see this (via the embed view)

![image](https://cloud.githubusercontent.com/assets/814322/15872423/33f912da-2cae-11e6-88b9-4ac53f555edf.png)

I think likely this is the same issue on NeuroVault server - @chrisfilo maybe try uninstalling all old versions, and re-installing. I put the package on [pip](https://pypi.python.org/pypi/nidmviewer) so we can better manage versions.

**Comment by chrisfilo** [comment]
How could this happen in a Docker image - we are installing NIDM viewer
only once. Could you build NeuroVault image from scratch locally (with
latest version of the NIDM viewer) and see if this bug is still present?

PS production server is still using previous version of NIDM Viewer (see
Docker file) for details. This could also explain the problem.

**Comment by vsoch** [comment]
I don't know, but I can tell you with certainty that the template is old. I can view the source - here there is supposed to be the "no suprathreshold voxels" div and it's entirely missing:

![image](https://cloud.githubusercontent.com/assets/814322/15873076/bbb4dfc6-2cb1-11e6-8442-26d32be1a1f9.png)

The bug itself is because the variable "empty_images" is not defined, that should be here:

![image](https://cloud.githubusercontent.com/assets/814322/15873100/d4161ad0-2cb1-11e6-8ac5-1d79543fe20a.png)

**Comment by vsoch** [comment]
Yes using an old version would be the problem - the templates come from the installation folder.

**Comment by vsoch** [comment]
Sure, let me try building NeuroVault locally, and updating nidm-viewer

**Comment by vsoch** [comment]
Ah yes, the Dockerfile references an old version of the viewer:

      RUN pip install 'git+git://github.com/vsoch/nidmviewer.git@0.1'

I just made a new release, 0.1.1, and will update image and test.

**Comment by vsoch** [comment]
ah yes, remember this error (I believe I reported in the other thread):

![image](https://cloud.githubusercontent.com/assets/814322/15873545/0c62b4c8-2cb4-11e6-880b-ea2c20fd4f0f.png)

We cannot check empty images that have urls in the nidm based on a web address.

**Comment by chrisfilo** [comment]
Thanks for checking this. Let's disable the empty image check for now. Even
though such NIDM Results files are valid we they are not expected to be
common.

**Comment by vsoch** [comment]
ok, let me update the code, and test. I'm in agreement about this decision.

**Comment by vsoch** [comment]
@cmaumet here is the error I was talking about before with regard to why I chose to not read README / description from a file, it triggers this error with pip install from pypi directly:

![image](https://cloud.githubusercontent.com/assets/814322/15874270/3a2339e8-2cb7-11e6-87c3-54cfaa64e638.png)

**Comment by vsoch** [comment]
boum!

![image](https://cloud.githubusercontent.com/assets/814322/15874507/4a48bc66-2cb8-11e6-887a-019563b8fd6b.png)

**Comment by vsoch** [comment]
will submit PR with minor tweaks for this to work.

**Comment by cmaumet** [comment]
@vsoch: I could not reproduce the error:
```
$ pip freeze | grep nidmviewer
$ pip install nidmviewer
Collecting nidmviewer
Requirement already satisfied (use --upgrade to upgrade): pandas in ./anaconda/lib/python2.7/site-packages/pandas-0.18.1-py2.7-macosx-10.5-x86_64.egg (from nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): rdflib in ./anaconda/lib/python2.7/site-packages (from nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): numpy in ./anaconda/lib/python2.7/site-packages (from nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): rdflib-jsonld in ./anaconda/lib/python2.7/site-packages (from nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): rdfextras in ./anaconda/lib/python2.7/site-packages (from nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./anaconda/lib/python2.7/site-packages (from pandas->nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in ./anaconda/lib/python2.7/site-packages (from pandas->nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): isodate in ./anaconda/lib/python2.7/site-packages (from rdflib->nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): pyparsing in ./anaconda/lib/python2.7/site-packages (from rdflib->nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): SPARQLWrapper in ./anaconda/lib/python2.7/site-packages (from rdflib->nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): html5lib in ./anaconda/lib/python2.7/site-packages (from rdflib->nidmviewer)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./anaconda/lib/python2.7/site-packages (from python-dateutil->pandas->nidmviewer)
Installing collected packages: nidmviewer
Successfully installed nidmviewer-0.1.3
$ pip freeze | grep nidmviewer
nidmviewer==0.1.3
```

But from your error message it looks like `README.md` is not included in the package. Have you included this commit (https://github.com/vsoch/nidmviewer/pull/11/commits/5445f7b2d01666a9b1ad986f349cc3f6101190e7) into your current release? You might need to add `README.md` to the `MANIFEST.in` file. Let me know if that solves the issue!

**Comment by vsoch** [comment]
Because I fixed it  :)

**Comment by cmaumet** [comment]
Make sense :)

**Comment by vsoch** [comment]
try:
 
      sudo pip install nidmviewer==0.1.1

**Comment by vsoch** [comment]
I think the fix could be to include the README in the manifest, I will try that next time!

**Comment by cmaumet** [comment]
So how did you fix it? Did you use the `MANIFEST.in` file?

**Comment by vsoch** [comment]
I just included the description / python reqs in the file directly.

**Comment by cmaumet** [comment]
Okay, if you are happy with this approach!

**Comment by cmaumet** [comment]
@vsoch: just for the record, I just came across this: http://peterdowns.com/posts/first-time-with-pypi.html, according to the "setup.cfg" section, you need to add these lines to your `setup.cfg` file if your README is not in rst:
```
[metadata]
description-file = README.md
```
