### ISSUE TITLE
server error with edit metadata table

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/NeuroVault#526]
To reproduce, go to editmetadata view:

http://neurovault.org/collections/1029/editmetadata

![image](https://cloud.githubusercontent.com/assets/814322/15994286/d121b508-30b4-11e6-8061-2e5f52730239.png)

Enter 34 and then 48 under "No. of subjects" and click save.

Likely it's an issue with some value already in the data that is trying to be saved.

**Comment by chrisfilo** [comment]
This is the culprit: https://opbeat.com/neurovault/neurovault/errors/207/

**Comment by vsoch** [comment]
ok, the bug then is if the user clicks in a cell, and then erases the value, as it will return to the server as '' (empty string).

**Comment by chrisfilo** [comment]
Maybe replacing "" with None before saving would solve the problem with
casting?

**Comment by vsoch** [comment]
This seems logical - if the default value is anything other than Null, it would render in the table as such. I don't see a situation where we would be trying to fill in a value of None that isn't allowed either. We might miss cases if people enter empty spaces with the "" (eg, " ") and stripping first would result in an error if it's not a string field. Likely, the ideal would be to check for string, strip, then check if == "". We could probably still do well just checking for == "".

**Comment by burnash** [comment]
It turned out that Django's fields know when they are allowed to receive an empty string as a value. I used that information in the fix.
