### ISSUE TITLE
NIDM-Results support

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#55]
NIDM Results (http://nidm.nidash.org/specs/nidm-results_020.html) is a standard for describing results of neuroimaging analysis. It is currently supported by SPM12 which outputs nidm.zip files.

1. Users should be able to add nidm.zip files through the existing channels (upload archive, upload folder, add files).
2. nidm.zip files cannot be modified on the website - they can only be replaced or deleted
3. After uploading nidm.zip file should be unziped on the server and it's content should be accessible through normal HTTP calls. Two metadata files included in it .ttl and .prov include "atLocation" which should be updated by replacing the previous "./" with a "http://neurovault.org..." path.
4. API will expose the .ttl, .prov, and .nidm.zip (recreated after the modification)
5. The web view of .nidm.zip file after upload should consist of papaya viewers for each statistical map found in it (with corresponding contrast names). In the future this will be upgraded by the statistical results output and excursion set outline visualisation performed by a pure JavaScritpt NIDM-Results viewer developed externally.

Python library rdflib can be useful for taking querying .ttl files using SPARQL (for example to get statistical maps and the corresponding contrasts names). Example queries can be found here: https://github.com/incf-nidash/nidm/tree/master/nidm/nidm-results/query. 

Earlier version of SPM12 had a bug that requires a short replacement operation to be performed on .ttl files: https://github.com/NeuroVault/NeuroVault/blob/enh/nidm-r/neurovault/apps/statmaps/utils.py#L49

Example .nidm.zip files can be found here: https://03b635f15995375276571521c484a221c331857d.googledrive.com/host/0B77zr9yIiKOTM19GRkt2d3E0TXc/

The NIDMResults object which should be extended to provide this functionality is here: https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/apps/statmaps/models.py#L250

**Comment by infocortex** [comment]
completed in #90
