### ISSUE TITLE
Mouse captured by Papaya viewer in Collections view.

### ISSUE THREAD

**Issue by erramuzpe** [NeuroVault/NeuroVault#553]
Possible javascript problem.

Collections view (can not scroll with the mouse scrolling function, the papaya takes the input):

http://neurovault.org/collections/1425/

Image view (the papaya does not take the input if the mouse does not click the visor):

http://neurovault.org/collections/1425/pain_01.nidm

**Comment by erramuzpe** [comment]
Seems like the behaviour changed after [this](https://github.com/NeuroVault/NeuroVault/commit/aa1dec01108bf7def4f808be6d2a25f408683896) commit. I've been trying with 

` params["allowScroll"] = false;`

but I can't manage to solve it. I'm not very familiar with js...

**Comment by tyarkoni** [comment]
I'd recommend making this the top priority to fix; it's *very* annoying, and severely hampers functionality (e.g., the user can't scroll to the bottom of the datatable to view more than the first few images).

**Comment by chrisfilo** [comment]
One quick fix that might be worth trying is to update papaya. BTW Asier -
this bug was there for a long time even before the NIDM-Results
improvements.

**Comment by tyarkoni** [comment]
Updating papaya.js does indeed seem to fix it. Running tests now, will open PR if they pass.
