### ISSUE TITLE
Duplicate images in paginated API endpoint

### ISSUE THREAD

**Issue by burnash** [NeuroVault/NeuroVault#562]
It looks like `/collection/<id>/images/` endpoint sometimes returns same images on different pages.

In instance, an image with id [27630](neurovault.org/images/27630/) appears in 
http://neurovault.org/api/collections/1806/images/  (aka http://neurovault.org/api/collections/1806/images/?limit=100&offset=0) _and_ also in the results on the `next` page: http://neurovault.org/api/collections/1806/images/?limit=100&offset=100

I guess the inconsistency is caused by the missing ordering clause in the source queryset. I can fix that but I need to confirm what model field to use for ordering. I suggest `add_date` since it's a common field for all models derived from `BaseCollectionItem`.

**Comment by chrisfilo** [comment]
Good catch! add date is a good option, but you can also use pk/I'd.

**Comment by burnash** [comment]
I agree, pk/id is a better idea since it's already indexed.
