### ISSUE TITLE
Downloading of big collections

### ISSUE THREAD

**Issue by erramuzpe** [NeuroVault/NeuroVault#567]
Download fails for large collections (it's aborted after a certain amount of time). 

Here's an example: http://neurovault.org/collections/1952/

**Comment by erramuzpe** [comment]
[This](http://stackoverflow.com/questions/32411349/nginx-django-serving-large-files-3gb) might be what we need. I will work on it and report.

**Comment by erramuzpe** [comment]
@chrisfilo , I have a [solution](https://github.com/erramuzpe/NeuroVault/commit/38f1735d8ad6c5e9f024cbfc8ed87512da208a17). I made it work for big collections, with the 'X-Accel-Redirect' option, but it forces me to save the file and it takes some seconds to generate it. I can not do it in the fly (at least for now) but I will work on it.

**Comment by chrisfilo** [comment]
There are some problems with this solution:
- The time it takes to generate the file
- Redundancy of storage space:
    - Reusing already created zip files?
    - Deleting files that have been already downloaded?
- Concurrency: what happens when two users request the same collection at the same time?

If those can be sorted out I'm game, but streaming seems a better option. I think dropbox and google drive use streaming.

**Comment by erramuzpe** [comment]
Sure, I though about all these things too. Let me work on the streaming solution for some days :)

**Comment by erramuzpe** [comment]
It looks like there are 2 main options, 'Streaming' or 'Static content download'. 

-  Streaming:
     - Solved in [this](https://github.com/erramuzpe/NeuroVault/commit/3a32d0fa8b9f90ed79247c24fbbe5837b05fa72d) other branch, easy. Works for a 1.3GB collection (+3000 maps), so it should work for collections up to 4GB (the largest collection atm has +6000 images). 
     - Pros: Immediate download. Easy to solve.
     - Cons: Memory problems? (can't serve more files that in size sum more than the available ram). Threads busy until the transference is over.
 
[Some people](http://stackoverflow.com/questions/67454/serving-dynamically-generated-zip-archives-in-django)  discourage this option: 

> But beware, creating zip archives on each request is bad idea and this may kill your server (not counting timeouts if the archives are large). Performance-wise approach is to cache generated output somewhere in filesystem and regenerate it only if source files have changed. Even better idea is to prepare archives in advance (eg. by cron job) and have your web server serving them as usual statics.

> I suggest to use separate model for storing those temp zip files. You can create zip on-fly, save to model with filefield and finally send url to user. Advantages:
    -Serving static zip files with django media mechanism (like usual uploads).
    -Ability to cleanup stale zip files by regular cron script execution (which can use date field from zip file model).

-  Static content download:
     - This option would involve to check all the details you pointed out in the previous message and to decide how to deal with generated zip files (which also involves need for extra space).

**Comment by chrisfilo** [comment]
Ok - let's increase the max body size for now. Thanks for investigating!
