### ISSUE TITLE
NIDM number of results don't match

### ISSUE THREAD

**Issue by muschellij2** [NeuroVault/NeuroVault#603]
In the API for NIDM-results, I found:

https://neurovault.org/api/nidm_results/?limit=100&offset=300 returns a 500 error, but the count as per (https://neurovault.org/api/nidm_results) indicates the count is 356.   Also https://neurovault.org/api/nidm_results/?limit=56&offset=300 return 500.

The url of  
https://neurovault.org/api/nidm_results/?limit=25&offset=300 does not, 
nor does
https://neurovault.org/api/nidm_results/?limit=3&offset=350, but
https://neurovault.org/api/nidm_results/?limit=4&offset=350 does return a 500.  

So it seems as though something about record 354 is causing an internal error in the API.

**Comment by chrisfilo** [comment]
It seems one of the files is corrupted.
```
OSError: [Errno 2] No such file or directory: '/var/www/image_data/images/2488/spm_0001.nidm/FStatistic.nii.gz'
```

This is the problematic collection: https://neurovault.org/collections/2488/

https://opbeat.com/neurovault/neurovault/errors/242/

**Comment by chrisfilo** [comment]
The corrupted entry has been removed.
