### ISSUE TITLE
Adding images via API

### ISSUE THREAD

**Issue by adelavega** [NeuroVault/NeuroVault#612]
Good chance this is user error but I'm having a hard time pushing images to collections via the API.

Example command with token removed (

    curl -L -H "Authorization: Bearer [token]" -F "name=test" 
    -F "map_type=F" -F modality=OTHER" 
    -F "file=@/home/zorro/Downloads/lfc_70.nii.gz"
    http://neurovault.org/api/collections/3448/images

This simply returns the following and no file is added
    {"count":0,"next":null,"previous":null,"results":[]}

Trying a different file that is 1.5MB gives the error:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
</html>
```

Any clues?
Also, is there any documentation of the push routes of the API? api-docs seems to only cover GET.

**Comment by chrisfilo** [comment]
I shared a google doc with examples with you. Did you get it?

**Comment by adelavega** [comment]
Yep, thanks, I'm going off that. Authorization, creating a collection, and all `GET` routes are working for me.

In that doc there is only an example for uploading a `nidm.zip` file type, however. Also, `pynv` (Luke Chang's neurovault uploading library) is also failing on this specific command. The curl command there is basically the same as pynv. This has me wondering if it's a bug, or I'm missing something.

**Comment by adelavega** [comment]
Also sorry I had a copy paste error in the curl command, which I've fixed.

**Comment by chrisfilo** [comment]
Hmm... Could you try https?

Best,
Chris

**Comment by adelavega** [comment]
Very nice. That works. I'll alert `pynv` of this issue as well. In the meantime, I might just use that library as it seems to cover my functionality, but let me know if you think this should be merged into pyneurovault.

**Comment by bthirion** [comment]
Sorry, I am getting the same error uploading an image using pynv. 
```
APIError: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.11.5</center>
</body>
</html>
```
What should I do ? Thx,

**Comment by bthirion** [comment]
Oh, I was actually usings http, not https. Works better now...
