### ISSUE TITLE
Add link to password reset

### ISSUE THREAD

**Issue by nicholst** [NeuroVault/NeuroVault#670]
As I seem to have two NeuroVault accounts, I was just about to login in and remove one.  However, I can't remember the password, and now it seems there is no password recovery option (though from #278 I can see there used to be one).

Is it hidden somewhere?  All I see is this...

<img width="1200" alt="screen shot 2018-10-21 at 11 45 32" src="https://user-images.githubusercontent.com/5155907/47265894-dee7b200-d526-11e8-9f86-8a505ca7596c.png">

**Comment by chrisfilo** [comment]
http://neurovault.org/accounts/password/reset/

**Comment by me-pic** [comment]
Hello !

I'm facing the same problem i.e. can't remember my password, but there is no password recovery option on the login page and the link previously shared in that issue (http://neurovault.org/accounts/password/reset/) is not working for me (page not found error). Can somebody help me ? 

Thank you !

**Comment by adelavega** [comment]
@rwblair Can you take a look please?

Looks like we broke this in the upgrade

**Comment by me-pic** [comment]
Hello ! I was just wondering if you had any updates regarding the reset password link. 
Thank you so much for your time :)

**Comment by adelavega** [comment]
Thanks for the reminder. I will ping the developer tomorrow!

**Comment by adelavega** [comment]
The NeuroVault developer @rwblair is out this week but we will take a look as soon as we can!

**Comment by rwblair** [comment]
Sorry for the delay, there were a couple separate problems, conflicts with package auth upgades, and broken/changed smtp credentials and settings.
Password change link now:
https://neurovault.org/password_reset/

I linked to it on the login page and was able to get a reset email and change my password using it. @me-pic let me know if you can do the same, particularly curious if you receive the password reset email.

**Comment by me-pic** [comment]
Hi @rwblair ! It worked ! Thank you so much :blush:

**Comment by adelavega** [comment]
@rwblair Can you confirm this is working now and we can close this issue?
