### ISSUE TITLE
Error when saving collection: KeyError: 'HTTP_ORIGIN'

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#70]
Internal Server Error: /collections/YFWCSZGJ/edit
	Traceback (most recent call last):
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
	    response = wrapped_callback(request, *callback_args, **callback_kwargs)
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
	    return view_func(request, *args, **kwargs)
	  File "./neurovault/apps/statmaps/views.py", line 129, in edit_collection
	    'url': request.META['HTTP_ORIGIN'] + collection.get_absolute_url(),
	KeyError: 'HTTP_ORIGIN'
	
	Request repr():
	<WSGIRequest
	path:/collections/YFWCSZGJ/edit,
	GET:<QueryDict: {}>,
	POST:<QueryDict: {u'echo_time': [u''], u'number_of_rejected_subjects': [u''], u'inclusion_exclusion_criteria': [u''], u'group_comparison': [u'1'], u'subject_age_max': [u''], u'used_dispersion_derivatives': [u'1'], u'used_intersubject_registration': [u'1'], u'intrasubject_estimation_type': [u''], u'field_of_view': [u''], u'order_of_preprocessing_operations': [u''], u'smoothing_type': [u''], u'subject_age_min': [u''], u'name': [u'EADC_PET'], u'length_of_blocks': [u''], u'used_orthogonalization': [u'1'], u'used_b0_unwarping': [u'1'], u'used_temporal_derivatives': [u'1'], u'software_package': [u''], u'scanner_model': [u''], u'high_pass_filter_method': [u''], u'proportion_male_subjects': [u''], u'number_of_imaging_runs': [u''], u'interpolation_method': [u''], u'group_repeated_measures_method': [u''], u'motion_correction_software': [u''], u'used_motion_regressors': [u'1'], u'functional_coregistered_to_structural': [u'1'], u'motion_correction_interpolation': [u''], u'type_of_design': [u''],
	  u'optimization_method': [u''], u'hemodynamic_response_function': [u''], u'group_model_type': [u''], u'used_slice_timing_correction': [u'1'], u'intrasubject_modeling_software': [u''], u'target_template_image': [u''], u'resampled_voxel_size': [u''], u'object_image_type': [u''], u'group_description': [u''], u'functional_coregistration_method': [u''], u'length_of_trials': [u''], u'DOI': [u''], u'number_of_subjects': [u''], u'used_motion_correction': [u'1'], u'private': [u'False'], u'pulse_sequence': [u''], u'used_high_pass_filter': [u'1'], u'orthogonalization_description': [u''], u'acquisition_orientation': [u''], u'order_of_acquisition': [u''], u'group_repeated_measures': [u'1'], u'motion_correction_reference': [u''], u'group_model_multilevel': [u''], u'number_of_experimental_units': [u''], u'handedness': [u''], u'coordinate_space': [u''], u'submit': [u'Save'], u'transform_similarity_metric': [u''], u'repetition_time': [u''], u'slice_thickness': [u''], u'length_of_runs': [u''], u'soft
	 ware_version': [u''], u'autocorrelation_model': [u''], u'b0_unwarping_software': [u''], u'intersubject_transformation_type': [u''], u'quality_control': [u''], u'used_smoothing': [u'1'], u'smoothing_fwhm': [u''], u'intrasubject_model_type': [u''], u'matrix_size': [u''], u'optimization': [u'1'], u'group_inference_type': [u''], u'subject_age_mean': [u''], u'used_motion_susceptibiity_correction': [u'1'], u'contributors': [u''], u'skip_factor': [u''], u'used_reaction_time_regressor': [u'1'], u'group_modeling_software': [u''], u'parallel_imaging': [u''], u'intersubject_registration_software': [u''], u'csrfmiddlewaretoken': [u'SlNH2epUZ59kFSnL1IO86Vw3SCtW6mq0'], u'nonlinear_transform_type': [u''], u'description': [u''], u'field_strength': [u''], u'group_estimation_type': [u''], u'target_resolution': [u''], u'slice_timing_correction_software': [u''], u'scanner_make': [u''], u'flip_angle': [u''], u'motion_correction_metric': [u'']}>,
	COOKIES:{'__utma': '90927109.1035651084.1418906064.1418906064.1418906064.1',
	 '__utmb': '90927109.1.10.1418906064',
	 '__utmc': '90927109',
	 '__utmz': '90927109.1418906064.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)',
	 '__uvt': '',
	 'csrftoken': 'SlNH2epUZ59kFSnL1IO86Vw3SCtW6mq0',
	 'sessionid': 'aj9iruj9esgh3ko2k1i20o84v0dqal2y',
	 'uvts': '1qOaSuRoqrgkVuxl'},
	META:{'CONTENT_LENGTH': '2023',
	 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
	 u'CSRF_COOKIE': u'SlNH2epUZ59kFSnL1IO86Vw3SCtW6mq0',
	 'DOCUMENT_ROOT': '/var/www',
	 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
	 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
	 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
	 'HTTP_CONNECTION': 'keep-alive',
	 'HTTP_CONTENT_LENGTH': '2023',
	 'HTTP_CONTENT_TYPE': 'application/x-www-form-urlencoded',
	 'HTTP_COOKIE': '__uvt=; csrftoken=SlNH2epUZ59kFSnL1IO86Vw3SCtW6mq0; sessionid=aj9iruj9esgh3ko2k1i20o84v0dqal2y; __utma=90927109.1035651084.1418906064.1418906064.1418906064.1; __utmb=90927109.1.10.1418906064; __utmc=90927109; __utmz=90927109.1418906064.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); uvts=1qOaSuRoqrgkVuxl',
	 'HTTP_HOST': 'neurovault.org',
	 'HTTP_REFERER': 'http://neurovault.org/collections/YFWCSZGJ/edit',
	 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0',
	 'PATH_INFO': u'/collections/YFWCSZGJ/edit',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '129.195.251.202',
	 'REMOTE_PORT': '53522',
	 'REQUEST_METHOD': 'POST',
	 'REQUEST_URI': '/collections/YFWCSZGJ/edit',
	 u'SCRIPT_NAME': u'',
	 'SERVER_NAME': 'neurovault.org',
	 'SERVER_PORT': '80',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'UWSGI_APPID': 'neurovault.org|',
	 'uwsgi.core': 2,
	 'uwsgi.node': 'neurovault.org',
	 'uwsgi.version': '2.0.8',
	 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f5288453420>,
	 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
	 'wsgi.input': <uwsgi._Input object at 0x7f525eb09420>,
	 'wsgi.multiprocess': True,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}>

**Comment by infocortex** [comment]
fixed in ec3cafc
