### ISSUE TITLE
typos and broken links in the API documentation

### ISSUE THREAD

**Issue by koudyk** [NeuroVault/NeuroVault#735]
I found 2 small problems with links on the [API documentation page](https://www.neurovault.org/api-docs):
1. in the example for `/api/images/{pk}/`, the pk value in the visible text and the value in the link don't match, and neither work. 
2. in the examples for `/api/collections/{pk}/` and `/api/collections/{pk}/images`, the pk value in the visible text is 20, but the value in the link is 287.

**Comment by rwblair** [comment]
fixed in #736 

Thank you @koudyk !
