### ISSUE TITLE
creating personal tokens

### ISSUE THREAD

**Issue by jdkent** [NeuroVault/NeuroVault#780]
this is a place to track how personal tokens are created and what changes need to be made for personal tokens to work:

https://github.com/NeuroVault/NeuroVault/blob/2fb00380f2ce38d1f986b75e3b1c4ecd6fa9318b/neurovault/apps/users/views.py#L110-L122

`AccessToken` is imported from oauth2_provider which is installed from [django-oauth-toolkit](https://github.com/jazzband/django-oauth-toolkit)

https://github.com/NeuroVault/NeuroVault/blob/2fb00380f2ce38d1f986b75e3b1c4ecd6fa9318b/compose/django/requirements.txt#L30

in which the last listed version of django-oauth-toolkit was 0.10.0
https://github.com/NeuroVault/NeuroVault/commit/405dbfd3027ce79f1f1012c559254a91dd14dc7f#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L38

Talking with alejandro, it is fine to invalidate all existing keys and start fresh. (no has complained thus far about not being able to use tokens, so invalidating existing tokens and starting over seems okay)

**Comment by jdkent** [comment]
Supposed plan of action:

- install 1.2.0
- run `manage.py migrate`
- upgrade to 2.1.0?

source: https://django-oauth-toolkit.readthedocs.io/en/latest/changelog.html#id54

then read over breaking changes for 2.0.0 (do not currently know which ones are relevant):
https://django-oauth-toolkit.readthedocs.io/en/latest/changelog.html#id10

**Comment by jdkent** [comment]
potential relevant error: https://github.com/jazzband/django-oauth-toolkit/issues/1209

(which would necessitate upgrade to 2.2.0)

**Comment by rwblair** [comment]
fixed in #783
