### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by annikabrueckner** [NeuroVault/NeuroVault#813]
Hi there, 
since today, I am no longer able to open the https://neurovault.org/ website (downloading the brain mask). I've tried it with different devices and different WLAN-options - however, it seems that the webpage is down. Can you fix the issue? 
Thanks a lot. :)

**Comment by annikabrueckner** [comment]
Website is down again ... can you fix?

**Comment by caneuro** [comment]
The https://neurovault.org/ website is not working. Can you please fix this soon, since I need to access our data repository.

**Comment by adelavega** [comment]
Service has been restored
