### ISSUE TITLE
update DataTables plug-in and associated code

### ISSUE THREAD

**Issue by tyarkoni** [NeuroVault/NeuroVault#83]
DataTables is out of date.  Version 1.9 uses an old clunky API. Should update to 1.10 and fix the associated code to take advantage of the cleaner API.

**Comment by chrisfilo** [comment]
View my collections, view all collection, collection details (images table) should take advantage of the new paginated API. This will require a new API path /api/collections/1/images listing all images for a single collections. This should also help with handling very big collections in the API.

**Comment by tyarkoni** [comment]
I probably won't have time to work on this in the next month, but if you look at the PR in #93, there shouldn't be much that has to be changed, and this might be a good time to update the other stuff.

**Comment by chrisfilo** [comment]
This has been fixed.
