### ISSUE TITLE
remove unused NSViewer/coffeescript code

### ISSUE THREAD

**Issue by tyarkoni** [NeuroVault/NeuroVault#84]
I notice there's a bunch of legacy NSViewer/CoffeeScript code in the templates. I assume this stuff can be removed safely, right? If you're not using my viewer any more, let me know and I'll do some cleanup, as it makes the templates unnecessarily confusing.

**Comment by abitrolly** [comment]
This also adds Node dependency - https://github.com/NeuroVault/NeuroVault/pull/635
