### ISSUE TITLE
Problems with add/edit images dialog

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#95]
Steps to replicate:
1. create a new collection
2. press edit images
3. press add statistic map (don't fill any fields)
4. press add atlas (don't fill any fields)
5. select first "[new image]" from the list 
6. select second "[new image]" from the list

results the form on the right does not change, selecting anything on the list does not seem to have any influence. Similar behaviour happens when editing a collection that already has some files

**Comment by chrisfilo** [comment]
@infocortex could you have a look?

**Comment by infocortex** [comment]
sorry, that should not have hit production.  fixed in pr #97
