### ISSUE TITLE
task queueing system for subprocess calls

### ISSUE THREAD

**Issue by infocortex** [NeuroVault/NeuroVault#99]
Several features require calling an external binary with possibly long running times, which should ideally be run in a separate process.  It would be good to add a asynchronous task queue for managing subprocesses so they can be decoupled from the request lifecycle.  This would be used for pycortex generation, upload_zip, upload_folder, FEAT parsing, and NIDM parsing.

I often use Celery with Rabbitmq (amqp) as the message broker, but amqp is a bit complex and probably overkill.  For a more simple, lightweight addition to the stack, I think we'd be better off using Redis over Rabbitmq as the messaging backend for Celery.

http://celery.readthedocs.org/en/latest/django/
http://celery.readthedocs.org/en/latest/getting-started/brokers/redis.html
http://celery.readthedocs.org/en/latest/tutorials/daemonizing.html

The celery django app can be daemonized with a sysv init script, or managed with systemd.  The prerequisites and configuration will be added to puppet, along with the necessary configuration for Redis.

**Comment by chrisfilo** [comment]
In terms of pycortex generation this will definitely be useful, but I'm not sure if it is worth the effort considering it will cut the loading time only by a couple of seconds.

The four other use cases (upload_zip, upload_folder, FEAT parsing, and NIDM parsing) require user input when done. Ideally we would like to provide some progress bar or another way of letting the user know that this is taking some time, but are on a good track. This applies to big uploads as well. Would this require celery? 

I don't think any of these task should be taking so much time that would justify telling the user that we will email them when we are finished.

**Comment by infocortex** [comment]
Yeap, no need for email notifications, etc, the current UI and views can be
used without major changes:

 - The form is submitted via javascript.
 - The page is dimmed behind an overlay with a loading icon, or progress
bar.  (Progress bar when its possible to accurately estimate progress.)
 - A javascript method polls the server for completion
 - After completion, one of two patterns:
   - the form is updated via javascript with errors and notifications
   - or, the page is reloaded, and the form errors and notifications are
loaded from the main request.

Django has a built in messaging feature to pass updates and modal
notifications via cookie, which works well with Bootstrap.

The load time doesn't really change, as the page still idles while the task
is running.  But the benefits are:
 -scalability, if the site is ever run in clustered/cloud situation, the
task queue comprises a separate cpu/instance pool from the webapp itself.
 -UI feedback is provided instead of a white loading page, so user knows
things are ok while the page hangs in an empty loading state
 -and most importantly, you can safely serve requests that get into the
30-60sec or greater range, without timeouts in the browser, or network
sockets closing, etc.

But, since the stuff we have to process does not take very long, its
probably only marginally needed for NV, more of a nice-to-have thing that
would provide robust support for large files, large collections in
pycortex, etc.


On Tue, Jan 6, 2015 at 4:23 PM, Chris Filo Gorgolewski <
notifications@github.com> wrote:

> In terms of pycortex generation this will definitely be useful, but I'm
> not sure if it is worth the effort considering it will cut the loading time
> only by a couple of seconds.
>
> The four other use cases (upload_zip, upload_folder, FEAT parsing, and
> NIDM parsing) require user input when done. Ideally we would like to
> provide some progress bar or another way of letting the user know that this
> is taking some time, but are on a good track. This applies to big uploads
> as well. Would this require celery?
>
> I don't think any of these task should be taking so much time that would
> justify telling the user that we will email them when we are finished.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NeuroVault/NeuroVault/issues/99#issuecomment-68959466>
> .
>



-- 
*Gabriel Rivera*

InfoCortex UG
rivera@infocortex.com

+49 (0) 176 7223 1002
+1 917.375.0045

Friedensstraße 11/Kaiserplatz
D-60311 Frankfurt am Main
www.infocortex.com

**Comment by vsoch** [comment]
I gave this a first go, and on my virtual machine I have it working (so far!)

https://github.com/vsoch/NeuroVault/blob/enh/image_comparison/neurovault/CELERY_README.md

- I'm using celery with redis backend, saving results, and configuration options are integrated into django settings.
- The choice of how to start the server seems to have many options, and I tested from command line, and then found a django module that will do it for me.  This of course could be however you like (Gabriel mentioned something about systemd?)
- I had permissions errors with the log files for celery. The default goes to PWD, so I just let them be there :) 
- My dinky test tasks work, I'm next going to try making some "real" tasks (generating glass brain images and the correlation matrices).
- I don't know why it's called celery. It seems like the C looks like a section of celery, but now we have a chicken and egg problem!

**Comment by vsoch** [comment]
And looking at this log on here, I didn't mean to unassign infocortex, I think we can work on together. I wanted to update here that I was going to give it a shot, and that seemed like the right way to go about it.

**Comment by infocortex** [comment]
Hi @vsoch, thanks nice work, this will help us along the way to adding queueing site-wide.

I can probably focus on:
-review of this procedure, suggestions and tweaks
-refactoring the uploading and upload processing code to be OO, centralized, and celery-taskable 
-the Javascript/client side of things, how tasks are instantiated and tracked with ajax requests
-Daemonization, logging and the needed Puppet modifications

**Comment by infocortex** [comment]
welp,I guess you can't assign multiple people.  Just subscribing works well enough, though :  }

**Comment by vsoch** [comment]
haha, ok :O)

**Comment by vsoch** [comment]
I am going to need some help getting the celery to work from within NeuroVault.  I can get it to work when I do manage.py shell, but when I add a line of code to models.py (so supposedly the same thing happens when an image is uploaded) it doesn't work.  Here is my workflow:
     
     // open up a vagrant terminal one:
     sudo service uwsgi restart  // must be done each time, as well as
     python manage.py celeryd -l INFO // I do this in its own window so I can see the celery output, live

     // open up a vagrant terminal two:
    cd /opt/nv_env/NeuroVault
    source bin/activate
    python manage.py shell

Then I start here https://github.com/vsoch/NeuroVault/blob/enh/image_comparison/neurovault/apps/statmaps/tests/test_celery.py#L4 and manually test generating the glass brains.  It works, and I see the output images in the folders under "image_data" and also a successful job note in my terminal window 1.  However, adding this same function call to (where I think) it should be:

https://github.com/vsoch/NeuroVault/blob/enh/image_comparison/neurovault/apps/statmaps/models.py#L221

Doesn't do anything at all. I don't see any output from my celery. I think it could be that:
- the image.pk is not assigned? (but I would see an error)
- the celery I am running with celeryd is not properly linked up to the "deployed" (uwsgi) app? For example, if I open a third window and do 

     /opt/nv_env/bin/celery status
     Error: No nodes replied within time constraint.
     
So I tried running it "the other way"

     /opt/nv_env/bin/celery --app=neurovault.celery:app worker --loglevel=INFO
     /opt/nv_env/bin/celery status
     Error: No nodes replied within time constraint.
 
Still nothing. This seems like something that would be helpful to have more insight to how django is setup (which I don't yet), so I'm hopeful you and Chris might have some insight! Let me know if there is something different that I might try - for now I just generated the glassbrains with celery via manage.py (which works) and so I can move forward with generating a correlation matrix, and then an interface to show the rankings.

**Comment by infocortex** [comment]
To get the glassbrain generation connected to the webapp, you need to override the Image model's `save()` method.  (The `create()` method is actually a class method (non-instanced) to create a generic image.)


```python
class Image(PolymorphicModel, BaseCollectionItem):
 
   < ... snip ... >
  
    def save(self):
        super(Image, self).save()
        generate_glassbrain_image.apply_async([self.pk])

```
That should work with the rest of your Celery integration.

We'll probably need to do a wee bit of manual merging, but in general you should be ok with matching the celery-related parts of  `settings.py`, `celery.py`, and `tasks.py` in my [working branch](https://github.com/infocortex/NeuroVault/compare/NeuroVault:master...infocortex:enh/celery?expand=1) (I copied in your glass brain code as test.)  Its mostly the same, but there are few relevant changes, see comments: https://github.com/infocortex/NeuroVault/commit/a70d2d97459b90535925adbebcfcefe47e43d118
